//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _142666_L_LO {
            get {
                object obj = ResourceManager.GetObject("_142666_L_LO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap affordable_space_adventures {
            get {
                object obj = ResourceManager.GetObject("affordable_space_adventures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affordable Space Adventures is a stealth puzzle spaceship simulator. Control your craft solo or in a crew of up to three players. The Wii U GamePad™ is your Heads Down Display and gives you precise control over all the internal systems of the ship. Tweak the thrusters, antigravity, stabilizer and many more systems in order to successfully navigate a hostile planet and sneak past alien robots. Explosions, engine shutdowns, blown fuses and implosions may occur.
        ///In co-op mode, players must coordinate as a cre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AffordableSA {
            get {
                return ResourceManager.GetString("AffordableSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap amiibo_tap {
            get {
                object obj = ResourceManager.GetObject("amiibo_tap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover definitive moments of classic Nintendo games while exploring the company&apos;s catalogue and legacy. Simply tap any amiibo™ figure to the Wii U™ GamePad controller to unlock scenes from NES™ and Super NES™ Wii U Virtual Console™ titles! You never know—the next game you try may become one of your new all-time favorites!
        ///Grab an amiibo from your collection and tap it to the GamePad to receive a gift! Each gift contains select scenes from a random NES or Super NES game included in this software&apos;s selecti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AmiiboTap {
            get {
                return ResourceManager.GetString("AmiiboTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap animal_crossing_amiibo_festival {
            get {
                object obj = ResourceManager.GetObject("animal_crossing_amiibo_festival", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Animal Crossing: amiibo Festival game is a brand-new way to play with your favorite Animal Crossing characters. Your amiibo figures are front-and-center in this party game, and you’ll get to use them with fun content. Bring to life an expansive and dynamic board game where the board is based on the months of the year like the core Animal Crossing series. The goal? Make your villager the happiest in town and party hard with your friends.
        ///Features:
        ///Party with favorite Animal Crossing characters like Isa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AnimalCrossingAF {
            get {
                return ResourceManager.GetString("AnimalCrossingAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armillo is a unique, fun rolling platforming game with a sci-fi parallel universe theme. It features a massive amount of gameplay elements. For one, there is the regular 3D world, followed by a bonus stage on the moon. Then there is the evil parallel universe, and special 2D speed-run inspired worlds. Lots of unexpected deadly twists, and surprises await! The star of the game features a space armadillo named Armillo. He&apos;s not your usual armadillo as he&apos;s capable of blasting off to space in order to travel f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Armillo {
            get {
                return ResourceManager.GetString("Armillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap armillo_cover {
            get {
                object obj = ResourceManager.GetObject("armillo_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bayonetta_2 {
            get {
                object obj = ResourceManager.GetObject("bayonetta_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The witching hour strikes again. Brimming with intricate battles that take place in, on and all over epic set pieces, Bayonetta 2 finds our sassy heroine battling angels and demons in unearthly beautiful HD. You&apos;re bound to love how it feels to string together combos with unimaginable weapons and to summon demons using Bayonetta&apos;s Wicked Weave in this frantic stylized action game. Bayonetta 2 is a Wii U exclusive.
        ///Features:
        ///Initiate the new Umbran Climax technique to temporarily summon demons and boost Ba [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Bayonetta2 {
            get {
                return ResourceManager.GetString("Bayonetta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blocky_bot {
            get {
                object obj = ResourceManager.GetObject("blocky_bot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump your way through a wacky world of Robots, Wizards, Ninjas and the first ever playable box of robotic French Fries! Blocky Bot is a brand new super action mini platformer for Wii U™, from the same team that brought you Paper Monsters Recut. Test your platforming skills and reflexes by collecting Bits and Bytes to unlock new characters and themes and push yourself for the best score and blocky bragging rights!
        ///--FEATURES--
        ///Endless 3D platformer gameplay combined with awesome robot style.
        ///Tons of origi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlockyBot {
            get {
                return ResourceManager.GetString("BlockyBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Box_NA___Mario_Kart_8 {
            get {
                object obj = ResourceManager.GetObject("Box_NA___Mario_Kart_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Captain_toad {
            get {
                object obj = ResourceManager.GetObject("Captain_toad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intrepid Captain Toad sets off on his own adventure for the very first time through a wide variety of tricky, enemy-infested, maze-like stages to find hidden gems and nab elusive gold stars.
        ///FEATURES:
        ///Equipped with nothing more than a neck scarf, backpack and oversized head lamp, Captain Toad finds hidden gems, coins and power-ups on his way to the gold star at the end of each tricky, trap-filled stage.
        ///Captain Toad isn&apos;t particularly fast or strong. He can&apos;t jump and he has no super powers. But he k [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaptainToadTT {
            get {
                return ResourceManager.GetString("CaptainToadTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cube_life {
            get {
                object obj = ResourceManager.GetObject("cube_life", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Life: Island Survival is the first block building open-world survival game for the Nintendo Wii U.
        ///In Creative Mode, the game will allow players to build constructions in 3D generated game worlds.
        ///In Survival Mode, the player must maintain health, explore caves, gather resources, and craft tools on an unknown island. Get food, explore and build during the day. Hide, fight, and surive as night falls on the island.
        ///Key Feature v1.1:
        ///Block building open-world survival game
        ///Creative Mode
        ///Survival Mod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CubeLife {
            get {
                return ResourceManager.GetString("CubeLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Donkey Kong and his friends save their home and banana hoard from marauding Vikings in theDonkey Kong Country™: Tropical Freeze game from Retro Studios. All the challenging ground-pounding, barrel-blasting, side-scrolling mine cart action from the Donkey Kong Country series is back along with a bushel of new game play elements and features.
        ///Features:
        ///Dixie Kong is back to join the adventure as a playable character alongside Diddy Kong. Either can buddy up with Donkey Kong, and each character offers a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DKCountryTF {
            get {
                return ResourceManager.GetString("DKCountryTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap donkey_kong_country_tropical_freeze {
            get {
                object obj = ResourceManager.GetObject("donkey_kong_country_tropical_freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dr__luigi {
            get {
                object obj = ResourceManager.GetObject("Dr__luigi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zap viruses in a falling block puzzle game featuring Dr. Luigi™!
        ///There’s a new doctor in the house! Dr. Mar—or, uh, Dr. Luigi is a new twist on this classic virus-popping puzzle game! Use new L-shaped pills in a brand new game mode and compete with players locally or online.*
        ///Drop pills the usual way, or get a second opinion with the Wii U GamePad controller. Virus Buster mode lets you position falling pill segments with the touchscreen and stylus to place them wherever you want. Use L-shaped pills carefu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DrLuigi {
            get {
                return ResourceManager.GetString("DrLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap family_party_30_games {
            get {
                object obj = ResourceManager.GetObject("family_party_30_games", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusively for the Wii U™ system from Nintendo, Obstacle Arcade lets players participate in over 30 party games specifically designed for multiplayer. Delivering an unmatched combination of variety and value, it features dozens of hysterical obstacle courses, popular sporting events, and arcade and brain challenges.
        ///Family Party: 30 Great Games Obstacle Arcade takes players to “Family Party Land”, a magical island loaded with a combination of familiar games and over-the-top challenges. Dodge barrels, ride [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FamilyParty {
            get {
                return ResourceManager.GetString("FamilyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FAST_Racing_Neo_Key_Artwork {
            get {
                object obj = ResourceManager.GetObject("FAST_Racing_Neo_Key_Artwork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race through a futuristic sci-fi world at incredible speeds in FAST Racing NEO.
        ///Jump into the driver&apos;s seat of your anti-gravity vehicle and put your skills to the test in high octane competitions. Play locally with four of your friends in splitscreen or online against 8 players from all around the world.
        ///Race through abandoned mines in the depths of the earth, to dense jungle areas, futuristic cities, crossing vast deserts and finally up into the stratosphere and beyond. Become a legend and master all co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FastRacingNeo {
            get {
                return ResourceManager.GetString("FastRacingNeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fatal_frame_maiden_of_black_water {
            get {
                object obj = ResourceManager.GetObject("fatal_frame_maiden_of_black_water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Frame: Maiden of Black Water is comprised of three interconnected stories that converge to uncover the truth behind a recent string of tragic deaths in a forest marred by a history of suicides. As one of three people with the power of the Camera Obscura and the ability to see the shadows of those spirited away, you’ll explore the ruins of an eerie inn, a shrine filled with life-size dolls, and a lake full of dead priestesses. Each shadowy location is connected by a stream of water flowing throughout t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FatalFrameMoBW {
            get {
                return ResourceManager.GetString("FatalFrameMoBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap game_party_champions {
            get {
                object obj = ResourceManager.GetObject("game_party_champions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Party Champions is the fifth and latest installment of the widely successful Game Party franchise and available exclusively for Wii U. The game’s fun, pick-up and play style will appeal to experienced and new gamers alike. Using the system’s innovative new GamePad, players tilt, turn and touch the controller to play arcade, sports and party games in entirely new ways.
        ///Eight Classic Games: Players can enjoy arcade, sports and party games such as Ping Pong and Skill Ball, and modern favorites such as Ta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GamePartyChampions {
            get {
                return ResourceManager.GetString("GamePartyChampions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wario™ and his crazed team of developers are bringing you creative new ways to play with your Wii U™ GamePad controller! In Game &amp; Wario™, you&apos;ll shield yourself from suction-cup arrows, avoid detection as a sneaky thief, and share in the WarioWare™ fun with your friends and family in an experience you won&apos;t find anywhere else!
        ///Discover an astounding variety of unusual games that stretch the boundaries of your gaming imagination as you use the GamePad as a dance floor for a competitive dance-off, or fire a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GameWario {
            get {
                return ResourceManager.GetString("GameWario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GameWario1 {
            get {
                object obj = ResourceManager.GetObject("GameWario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Genei_Ibun_Roku_FE_Feature_Scans_15 {
            get {
                object obj = ResourceManager.GetObject("Genei_Ibun_Roku_FE_Feature_Scans_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Just_Dance_Disney_Party_2_cover {
            get {
                object obj = ResourceManager.GetObject("Just_Dance_Disney_Party_2_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Dance and Disney are back together, bringing the greatest dance game for the whole family with music from the hottest Disney Channel shows, in Just Dance®: Disney Party 2.
        ///Dance like the stars from the most popular Disney Channel shows and movies. With a great selection of family favorite songs, fun dances, and kid-friendly gameplay, children of all ages can dance along with family and friends.
        ///Just Dance 2016
        ///Release October 20, 2015
        ///Introducing Just Dance 2016® - the newest game from the top-sell [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JustDanceDP2 {
            get {
                return ResourceManager.GetString("JustDanceDP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kirby_and_the_rainbow_curse_cover_800 {
            get {
                object obj = ResourceManager.GetObject("kirby_and_the_rainbow_curse_cover_800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have the magic touch? Then guide Kirby as he sets off on grand adventures in a hand-sculpted clay world. Draw lines on the touch screen of the Wii U GamePad controller to create rainbow-colored clay ropes to move Kirby around freely, or tap him to attack enemies or blast through obstacles. Transformations include a submarine, rocket and tank. In underwater levels, Kirby dons a swim mask. If his power level gets too low, a clay bandage appears on his head.
        ///FEATURES:
        ///Kirby comes to life in a world of [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KirbyRC {
            get {
                return ResourceManager.GetString("KirbyRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lego_undercover {
            get {
                object obj = ResourceManager.GetObject("lego_undercover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the first time, the fan-favorite LEGO City vehicles and play sets come to life in LEGO® City Undercover, exclusively for the new Wii U console. Players assume the identity of Chase McCain, an undercover detective armed with clever disguises. The mission is to put a stop to the fiendish Rex Fury and end his crime wave in LEGO City. As players run, drive and even fly through the city, they’ll use the Wii U GamePad controller as a new police gadget.
        ///The Wii U GamePad is woven seamlessly into the game-play [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LegoCity {
            get {
                return ResourceManager.GetString("LegoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Information not yet available..
        /// </summary>
        public static string LoZ2016 {
            get {
                return ResourceManager.GetString("LoZ2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Legend of Zelda: The Wind Waker makes its glorious return on the Wii U console with gorgeous HD graphics and enhanced game features. In this timeless classic with a unique and colorful &quot;toon-shaded&quot; art style, players guide Link as he sets out on the massive Great Sea to find his kidnapped sister. You will sail the seas in search of lost islands, fight fearsome enemies, take on mighty bosses, and seek out the legendary Triforce.
        ///New Features:
        ///The Legend of Zelda: The Wind Waker HD features 1080p visua [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoZTheWindWaker {
            get {
                return ResourceManager.GetString("LoZTheWindWaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dark force, shrouded in twilight, has invaded the vast land of Hyrule. To restore light to the world, team up with the mysterious creature Midna and embrace the darkness to transform into a divine wolf. Fight through labyrinthine dungeons, survive puzzling traps and meet a cast of characters you’ll never forget in this legendary Zelda™ adventure.
        ///The Legend of Zelda™: Twilight Princess is a critically acclaimed masterpiece, set in a massive world bursting with life—but also shadow. A dark figure from the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoZTwilightPrincess {
            get {
                return ResourceManager.GetString("LoZTwilightPrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario_party_10 {
            get {
                object obj = ResourceManager.GetObject("mario_party_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mario_tennis_ultra_smash {
            get {
                object obj = ResourceManager.GetObject("mario_tennis_ultra_smash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race upside-down and along walls on anti-gravity tracks in the most action-fueled Mario Kart™ game yet! Take on racers across the globe and share videos of your greatest moments via Mario Kart TV.*
        ///Driving up a waterfall or across the ceiling can provide an intense adrenaline rush, but that’s not all anti-gravity is good for. It also provides a wild new gameplay mechanic: if you collide into other racers in zero-g, you’ll earn speed boosts worth bragging about. Luckily, you can upload and share your best m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarioKart8 {
            get {
                return ResourceManager.GetString("MarioKart8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser crashes the latest Mario Party, the first installment of the series on the Wii U console. In the new Bowser Party mini-games, play as Bowser himself and face off against up to four others playing as Mario and friends. Control Bowser using the buttons, motion controls and touch screen of the Wii U GamePad controller in different ways, and wreak havoc as Bowser in each mini-game while the other players strive to survive.
        ///FEATURES:
        ///Grab the GamePad and play as Bowser for the first time in the series.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarioParty10 {
            get {
                return ResourceManager.GetString("MarioParty10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compete with Mario™, Sonic and all your favorite characters in Rio de Janeiro, host of the Olympic Games in 2016. Gear up for the competition, and see if you’ve got what it takes to compete with the best in events like Soccer, Rugby and Beach Volleyball.
        ///Features:
        ///Compete in fun and exciting Olympic events set throughout host city Rio de Janeiro.
        ///Join Mario, Sonic and your favorite characters to take on challenging events like Soccer, Beach Volleyball, and Rugby.
        ///2016 marks the first Olympic Games appea [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarioSonic2016OG {
            get {
                return ResourceManager.GetString("MarioSonic2016OG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compete with friends in the multiplayer Mario Tennis: Ultra Smash game on the Wii U system. Along with the fun and dynamic gameplay known to the franchise, surprise your opponents with a new move to the series, the Jumpshot, which sends the ball flying down the court. Change the sport up with new Mega Battles, using the Mega Mushroom to gain an advantage over the competition. Claim your spot in Mario Tennis lore in singles (1v1) or doubles (2v2) as you play with and against family, friends or the CPU using  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarioTennisUSmash {
            get {
                return ResourceManager.GetString("MarioTennisUSmash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap New_Super_Luigi_U__NA_ {
            get {
                object obj = ResourceManager.GetObject("New_Super_Luigi_U__NA_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Mario nowhere to be found, it’s up to Luigi to save the day in a brand-new downloadable adventure that takes place in the world of New Super Mario Bros. U. Experience new gameplay challenges as you guide Luigi, complete with his high jump and unique slide, through all-new courses. Enjoy high replayability and satisfaction from mastering each course, and then share your triumphs via the Miiverse feature. Up to five players* can jump into the fun, with Nabbit taking the place of Mario as a playable chara [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewSuperLuigi {
            get {
                return ResourceManager.GetString("NewSuperLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Super Mario Bros. U is a new, side-scrolling adventure featuring Mario, Luigi, Toad … and your Mii character. Now’s your chance to step inside the Mushroom Kingdom and explore new worlds, new power-ups and new ways to play. Up to five players* can jump into the fun, with up to four people using Wii Remote controllers and one on the Wii U GamePad. The experience is different, depending on which controller is used..
        /// </summary>
        public static string NewSuperMarioBros {
            get {
                return ResourceManager.GetString("NewSuperMarioBros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nintendo_Land {
            get {
                object obj = ResourceManager.GetObject("Nintendo_Land", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nintendo_Wii_U_Super_Mario_3D_World_Front_Cover {
            get {
                object obj = ResourceManager.GetObject("Nintendo_Wii_U_Super_Mario_3D_World_Front_Cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo Land is a fun and lively virtual theme park filled with attractions based on popular Nintendo game worlds. Each attraction features unique and innovative game-play experiences made possible by the Wii U GamePad controller. Depending on the attraction, players can play solo, compete against other players, or even team up to play cooperatively. Up to five players can participate in dynamic multiplayer modes in select attractions.* The experiences change depending on whether players are using the Game [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NintendoLand {
            get {
                return ResourceManager.GetString("NintendoLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pikmin_3_Nintendo_America {
            get {
                object obj = ResourceManager.GetObject("Pikmin_3_Nintendo_America", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the Pikmin 3 game, players take command of three explorers and a legion of adorable Pikmin in a fight for survival. By employing the unique abilities of these tiny Pikmin creatures, players will solve puzzles, battle dangerous predators and recover food needed to save the explorers&apos; depleted home planet.
        ///Want more Pikmin? Download Pikmin™ Short Movies, directed by Shigeru Miyamoto, exclusively on Nintendo eShop.
        ///FEATURES:
        ///Discover the charming personalities of the plant-like Pikmin creatures as they c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pikmin3 {
            get {
                return ResourceManager.GetString("Pikmin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pokemon_rumble_u {
            get {
                object obj = ResourceManager.GetObject("pokemon_rumble_u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each morning, Capsules filled with Toy Pokémon are delivered to the Toy Shop. One day, some capsules filled with Toy Pokémon accidentally drops into the river—a river that sets them adrift to a far-off place. Intent on getting back to the Toy Shop, the Toy Pokémon start walking. Suddenly, a Toy Pokémon appears in front of them and challenges them to a battle! Why are the Toy Pokémon fighting each other? Will they make it back to the Toy Shop?
        ///Features:
        ///Battle and collect all 649 Pokémon in this over-the-t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PokemonRumble {
            get {
                return ResourceManager.GetString("PokemonRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pushmo_Screen_Shot_2014_06_04_09_29_11 {
            get {
                object obj = ResourceManager.GetObject("Pushmo_Screen_Shot_2014_06_04_09_29_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the fist-pumping joy of push-pull puzzle solving in the latest entry of the critically acclaimed Pushmo™ series! Block-based puzzles, charming characters, and a built-in community make the Pushmo World game endless fun for puzzle solvers of all ages.
        ///When a kindly old inventor creates a wondrous park filled with puzzling playgrounds called Pushmo, a little trickster traps Mallo’s friends inside! Now it&apos;s up to our hero, Mallo, to push, pull, and climb his way through 250 mind-bending Pushmo play [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PushmoWorld {
            get {
                return ResourceManager.GetString("PushmoWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rabbids_landwiiuyar1 {
            get {
                object obj = ResourceManager.GetObject("rabbids_landwiiuyar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason unknown to us, Rabbids decide to take over our beloved amusement park.
        ///We do not know their plan; we do not know their intentions. But one thing we are sure of: they are going to make the most of their day out by invading all the attractions!
        ///They don’t intend to queue like everyone else or stay seated during the whole journey!
        ///As Rabbids will always be Rabbids, you’ll see them misusing the rides, going bwaaah at a souvenir shop before stopping in an overpriced themed restaurant.
        ///So whet [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RabbidsLand {
            get {
                return ResourceManager.GetString("RabbidsLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runbow is a fast-paced action party game for up to 9 players! The world changes with each swipe of the background colour and if you can&apos;t see something it doesn&apos;t exist! Players can go head-to-head in Run, Arena, King of the Hill, and ColourMaster, or hone their skills on their own in Adventure or The Bowhemoth.
        ///Local and Online Nine-player Multiplayer – The biggest couch-multiplayer experience to come to Wii U™, ever!
        ///Six Great Game Modes – Challenge friends in King of the Hill, Arena, Run, or ColourMast [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Runbow {
            get {
                return ResourceManager.GetString("Runbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap runbow1 {
            get {
                object obj = ResourceManager.GetObject("runbow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SB_Rise_of_Lyric_NA_Box_Art {
            get {
                object obj = ResourceManager.GetObject("SB_Rise_of_Lyric_NA_Box_Art", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sing_party {
            get {
                object obj = ResourceManager.GetObject("sing_party", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the party started with SiNG Party, a new, interactive musical performance game that will get you and your guests singing and dancing well into the night. With dozens of popular songs to choose from, everyone from novice singers to experienced entertainers will be able to join in the fun. While one person steps up as the main performer, others can dance, sing and clap along with the prompts on the TV screen, making sure everyone at the party is rocking out together.
        ///In “Party” mode, the lead singer uses [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SingParty {
            get {
                return ResourceManager.GetString("SingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tale of youth and heroes guided by destiny
        ///Set in modern Tokyo, young people come together to weave an epic tale alongside heroes from an alternate world. This brand new RPG, developed by ATLUS, is infused with elements of the popular Fire Emblem series. In the struggle between the worlds of glamour and darkness, these young heroes rise to face the challenge.
        ///Features:
        ///Collaboration that blends the Shin Megami Tensei series with Fire Emblemcharacters.
        ///&quot;Mirages&quot;—beings of immeasurable power hailing fro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SMTxFireEmblem {
            get {
                return ResourceManager.GetString("SMTxFireEmblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Sonic Boom™: Rise of Lyric, Sonic and his friends Tails, Knuckles and Amy encounter an ancient tomb sealed deep within an island, where they come across a powerful snake-like villain named Lyric. The group must put aside their differences and work together as a team to save the world from Lyric’s evil plan and his army of war mongering robots!
        ///They will race across ancient ruins, the depths of the ocean and even back in time… This may be their biggest adventure yet. Do you have what it takes to help Son [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SonicBoomRoL {
            get {
                return ResourceManager.GetString("SonicBoomRoL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splatter enemies and claim your turf as the ink-spewing, squid-like characters called Inklings in Nintendo&apos;s new third-person action shooter game for the Wii U console.
        ///Compete in four-on-four matches, in which the goal is to get your ink on as many places as possible and claim your turf, all while strategically submerging yourself in your team&apos;s colors and blasting your enemies. This is a colorful and chaotic online third-person action shooter – exclusively on Wii U.
        ///FEATURES:
        ///Fresh content
        ///New weapons [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Splatoon {
            get {
                return ResourceManager.GetString("Splatoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap splatoon1 {
            get {
                object obj = ResourceManager.GetObject("splatoon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star_fox_zero {
            get {
                object obj = ResourceManager.GetObject("star_fox_zero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox, Falco, Peppy and Slippy save the Lylat system in this new deep space dogfighting adventure. Using the Wii U GamePad controller and the TV together creates a unique interface that allows players to experience the game with two different viewpoints within the Arwing – aim and shoot enemies in one direction while flying in another. This frees up the TV for a more cinematic flight experience. Then, pilot the Arwing with its new Walker transformation, along with the new Gyrowing and the Landmaster Tank, to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StarFoxZero {
            get {
                return ResourceManager.GetString("StarFoxZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap super_mario_maker {
            get {
                object obj = ResourceManager.GetObject("super_mario_maker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap super_marior_bros_u {
            get {
                object obj = ResourceManager.GetObject("super_marior_bros_u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mario experience of your dreams has arrived and is bursting with creativity... including yours! Play a near-limitless number of intensely creative Super Mario levels from players around the world. It’s easy enough to create your own levels with the Wii U GamePad controller that it may feel like you’re simply sketching out your ideas on paper, but you can now bring enemies and objects into a playable course in ways you could only dream of before. What was impossible in traditional Mario games is now impo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SuperMarioMaker {
            get {
                return ResourceManager.GetString("SuperMarioMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap The_Legend_of_Zelda_Twilight_Princess_Game_Cover {
            get {
                object obj = ResourceManager.GetObject("The_Legend_of_Zelda_Twilight_Princess_Game_Cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap The_Wind_Waker_HD_Boxart {
            get {
                object obj = ResourceManager.GetObject("The_Wind_Waker_HD_Boxart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wii_u_zelda {
            get {
                object obj = ResourceManager.GetObject("wii_u_zelda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii Fit U reinvents fitness fun again with the Wii U GamePad controller, Wii Balance Board accessory, and the new Fit Meter**. Carry the Fit Meter accessory to track daily activity, then sync it to your Wii U to compare accomplishments online***. With over 70 activities, Wii Fit U makes fitness so fun it motivates you to get active and stay active!
        ///Shape up with a wide range of fun activities including Yoga, Strength exercises, Balance Games, Dance, Aerobic activities, and more.
        ///Whether at home or on the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WiiFitU {
            get {
                return ResourceManager.GetString("WiiFitU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WiiFitUBoxart {
            get {
                object obj = ResourceManager.GetObject("WiiFitUBoxart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WiiPartyU {
            get {
                object obj = ResourceManager.GetObject("WiiPartyU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wonderful_101_us_wiiu_esrb_rendjpg_e969fd {
            get {
                object obj = ResourceManager.GetObject("wonderful_101_us_wiiu_esrb_rendjpg_e969fd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Wonder Red, leader of the Wonderful 100, you will unite your band of Wonderful Ones to morph into powerful transformations such as a fist, sword, glider, gun, and more to battle invaders throughout Blossom City and across the world. The Wonderful 100—and YOU—are the city&apos;s best weapon.
        ///Unite your horde of heroes and morph into powerful weapons to crush the invaders, or synthesize into bridges, chains, and other objects that help you move through the world&apos;s different environments.
        ///Explore each stage to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wonderful101 {
            get {
                return ResourceManager.GetString("Wonderful101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap xenoblade_chronicles_x {
            get {
                object obj = ResourceManager.GetObject("xenoblade_chronicles_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next massive sci-fi role-playing game from Monolith Soft, the creators of Baten Kaitos and Xenoblade Chronicles, comes exclusively to Wii U. A terrible intergalactic war leaves just a handful of Earth survivors trying to live in a beautiful yet hostile environment. Players engage in battles against powerful creatures of all forms and sizes using the deep battle system that builds on the triumphs of Xenoblade Chronicles for Wii.
        ///FEATURES:
        ///Riding and controlling a weaponized mech, players can explore ev [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XenobladeChroniclesX {
            get {
                return ResourceManager.GetString("XenobladeChroniclesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yoshi_s_woolly_world {
            get {
                object obj = ResourceManager.GetObject("yoshi_s_woolly_world", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set off with a friend* through a wild, woolly world in this grand Yoshi™ adventure! A treasure trove of clever handicraft stages are ready for you to explore. Unravel their secrets and color your world with a spectrum of yarn balls to knit new paths and get every last collectible.
        ///Knitting yarn, patchwork, and other handicraft materials combine into a whimsical and crafty backdrop for our knit Yoshi to explore. Instead of eggs, this time Yoshi tosses yarn balls that he can use to clear blocked paths, tangl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YoshisWW {
            get {
                return ResourceManager.GetString("YoshisWW", resourceCulture);
            }
        }
    }
}
